### ISSUE TITLE
What method do you use for mathematical modeling?

### ISSUE THREAD

**Issue by MrPlay123** [alexberndt/Quadrotor-Balancing-Pendulum-MPC#1]

**Comment by alexberndt** [comment]
Hi MrPlay123

The modelling implemented in this work is based on Euler-Lagrange mathematical modelling. You can find more details on the derivations here: https://ieeexplore.ieee.org/document/5980244

**Comment by MrPlay123** [comment]
Why is there no rate of pitch and roll angle  in the simulation image?

**Comment by alexberndt** [comment]
I am not exactly sure what you mean? The simulation definitely has varying pitch and roll angle (since this is considered in the dynamics of the quadrotor). 

Which "simulation image" are you referring to?

**Comment by MrPlay123** [comment]
![untitled3](https://user-images.githubusercontent.com/44824737/61936863-27edfa80-afc0-11e9-8ef8-2d5a43bd9092.jpg)
We only have roll angle γ but no rate of quadrotor body in this picture.

**Comment by alexberndt** [comment]
Oh I see. I decided only to plot the roll angle, not the rate in this case. But the roll angle state is still accessible in the code and can be plotted as well if desired.

**Comment by MrPlay123** [comment]
Can you help me plot it?

**Comment by alexberndt** [comment]
If you are running "reference_LQR.m" , you can see the function "functions/plot_2D_plots" is used to plot this plot you mentioned above (see line #100 of referene_LQR.m). In this function "plot_2D_plots", you can then access the plot for the pitch angle:

>         subplot 515;
>         stairs(time, states_trajectory(:,5), 'k-');  grid();
>         ylabel('$\beta$ [rad]','interpreter','latex');

State 5 is the roll, and 6 is the pitch rate in the states_trajectory variable. So just plot states_trajectory(:,6) instead.

Similarly, state 12 is the roll rate, and 11 is the roll angle in states_trajectory.

This is exactly the same for "reference_MPC.m"

**Comment by MrPlay123** [comment]
thank you

**Comment by MrPlay123** [comment]
![untitled3](https://user-images.githubusercontent.com/44824737/61951057-5d0b4480-afe2-11e9-8a62-81619f3c5567.jpg)
Why is it not 0 after 2 seconds in the Z-axis direction

**Comment by MrPlay123** [comment]
Besides LQR and MPC, what other ways can we balance the system？
