### ISSUE TITLE
Excuse me，Can you tell me how to obtain the state matrices A, B, C of the equation of state？according to the dynamic equation?

### ISSUE THREAD

**Issue by MrPlay123** [alexberndt/Quadrotor-Balancing-Pendulum-MPC#3]

**Comment by alexberndt** [comment]
For this, please refer to the original paper 

"A  model  predictive  controller  for  quadrocopter  state  interception" by Mueller and D'Andrea

 (http://www.flyingmachinearena.org/wp-content/publications/2013/mueECC13.pdf)
